{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 419 entries, 0 to 418\n",
      "Data columns (total 17 columns):\n",
      " #   Column               Non-Null Count  Dtype \n",
      "---  ------               --------------  ----- \n",
      " 0   GroupNo              419 non-null    int64 \n",
      " 1   Smooth_Presentation  419 non-null    int64 \n",
      " 2   Clear_Presentation   419 non-null    int64 \n",
      " 3   Comment_ton          419 non-null    object\n",
      " 4   Explain_CBD          419 non-null    int64 \n",
      " 5   Balanced             419 non-null    int64 \n",
      " 6   Kin_Explaination     419 non-null    int64 \n",
      " 7   Doseage              419 non-null    int64 \n",
      " 8   SideEffects          419 non-null    int64 \n",
      " 9   Bias                 419 non-null    int64 \n",
      " 10  Pros_Cons            419 non-null    int64 \n",
      " 11  Good_Job             419 non-null    int64 \n",
      " 12  Comment_overal       419 non-null    object\n",
      " 13  Research_Holes       419 non-null    int64 \n",
      " 14  Peer_Reviewed        419 non-null    int64 \n",
      " 15  Sufficent_Info       419 non-null    int64 \n",
      " 16  Comment_quality      419 non-null    object\n",
      "dtypes: int64(14), object(3)\n",
      "memory usage: 55.8+ KB\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_excel('CSV_W23.xlsx')\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n",
      "10\n",
      "11\n",
      "12\n",
      "13\n",
      "14\n",
      "15\n",
      "16\n",
      "17\n",
      "18\n",
      "19\n",
      "20\n",
      "21\n",
      "22\n",
      "23\n",
      "24\n",
      "25\n",
      "26\n",
      "27\n",
      "28\n",
      "29\n",
      "30\n",
      "31\n",
      "32\n",
      "33\n",
      "34\n",
      "35\n",
      "36\n",
      "37\n",
      "38\n",
      "39\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from jinja2 import Template\n",
    "\n",
    "# read data from CSV file into a pandas dataframe\n",
    "df = pd.read_excel('CSV_W23.xlsx')\n",
    "\n",
    "# group data by GroupNo\n",
    "grouped = df.groupby('GroupNo')\n",
    "\n",
    "# iterate through each group\n",
    "for group, data in grouped:\n",
    "    # calculate mean of integer columns for the group\n",
    "    means = data[['Smooth_Presentation', 'Clear_Presentation', 'Explain_CBD', 'Balanced', 'Kin_Explaination', 'Doseage', 'SideEffects', 'Bias', 'Pros_Cons', 'Good_Job', 'Research_Holes', 'Peer_Reviewed', 'Sufficent_Info']].agg(['mean', 'std'])\n",
    "    #means = data[['SmoothPresent', 'ClearPresent', 'Comment_ton', 'Explain_CBD', 'Balanced', 'Kin_Explain', 'Doseage', 'SideEffect', 'Bias', 'ProCon']].mean()\n",
    "    \n",
    "    # format mean and standard deviation values to two decimal places\n",
    "    means = means.round(2)\n",
    "\n",
    "    # extract only the mean values\n",
    "    score = means.loc['mean']\n",
    "    \n",
    "    # Calculate total score\n",
    "    total_score = score.sum()\n",
    "    \n",
    "    # Convert total score to a mark out of 120 as a percentage\n",
    "    mark = round(total_score / 120 * 100, 2)\n",
    "   \n",
    "    print(group)\n",
    "   \n",
    "    # create individual report for the group\n",
    "    template = Template(\"\"\"\n",
    "       <html>\n",
    "    <head>\n",
    "        <title>Group {{ group }}</title>\n",
    "        <style>\n",
    "            table {\n",
    "              border-collapse: collapse;\n",
    "              width: 80%;\n",
    "              margin: 0 auto;\n",
    "            }\n",
    "\n",
    "            th, td {\n",
    "              text-align: left;\n",
    "              padding: 8px;\n",
    "              border-bottom: 1px solid #ddd;\n",
    "            }\n",
    "\n",
    "            th {\n",
    "              background-color: #f2f2f2;\n",
    "            }\n",
    "\n",
    "            body {\n",
    "              max-width: 800px;\n",
    "              margin: 0 auto;\n",
    "              padding: 20px;\n",
    "              font-family: sans-serif;\n",
    "            }\n",
    "        </style>\n",
    "    </head>\n",
    "    <body>\n",
    "        <h1>Group {{ group }}</h1>\n",
    "        <h2>Summary of Scores:</h2>\n",
    "        <table>\n",
    "            <thead>\n",
    "                <tr>\n",
    "                    <th>Section</th>\n",
    "                    <th>Mean Score</th>\n",
    "                    <th>Standard Deviation</th>\n",
    "                </tr>\n",
    "            </thead>\n",
    "            <tbody>\n",
    "                {% for column in means.columns %}\n",
    "                <tr>\n",
    "                    <td>{{ column }}</td>\n",
    "                    <td>{{ means.loc['mean', column] }}</td>\n",
    "                    <td>{{ means.loc['std', column] }}</td>\n",
    "                </tr>\n",
    "                {% endfor %}\n",
    "            </tbody>\n",
    "        </table>\n",
    "        <h2>Peer Review Grade: {{ mark }} </h2>\n",
    "        <h4>Note* Pros_Cons and Good_Job are scored out of 5 everything else is out of 10</h4>\n",
    "        <h2>Feedback Presentation tone:</h2>\n",
    "        {% for feedback in data['Comment_ton'] %}\n",
    "        <p>{{ feedback }}</p>\n",
    "        {% endfor %}\n",
    "        <h2>Feedback Overal Presentation:</h2>\n",
    "        {% for feedback in data['Comment_overal'] %}\n",
    "        <p>{{ feedback }}</p>\n",
    "        {% endfor %}\n",
    "         <h2>Feedback Presentation Qaulity:</h2>\n",
    "        {% for feedback in data['Comment_quality'] %}\n",
    "        <p>{{ feedback }}</p>\n",
    "        {% endfor %}\n",
    "    </body>\n",
    "</html>\n",
    "\n",
    "    \"\"\")\n",
    "    html = template.render(group=group, means=means, mark=mark, data=data)\n",
    "    # save individual report as HTML file\n",
    "    with open(f'group_{group}_report.html', 'w') as f:\n",
    "        f.write(html)\n",
    "   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 419 entries, 0 to 418\n",
      "Data columns (total 17 columns):\n",
      " #   Column               Non-Null Count  Dtype \n",
      "---  ------               --------------  ----- \n",
      " 0   GroupNo              419 non-null    int64 \n",
      " 1   Smooth_Presentation  419 non-null    int64 \n",
      " 2   Clear_Presentation   419 non-null    int64 \n",
      " 3   Comment_ton          419 non-null    object\n",
      " 4   Explain_CBD          419 non-null    int64 \n",
      " 5   Balanced             419 non-null    int64 \n",
      " 6   Kin_Explaination     419 non-null    int64 \n",
      " 7   Doseage              419 non-null    int64 \n",
      " 8   SideEffects          419 non-null    int64 \n",
      " 9   Bias                 419 non-null    int64 \n",
      " 10  Pros_Cons            419 non-null    int64 \n",
      " 11  Good_Job             419 non-null    int64 \n",
      " 12  Comment_overal       419 non-null    object\n",
      " 13  Research_Holes       419 non-null    int64 \n",
      " 14  Peer_Reviewed        419 non-null    int64 \n",
      " 15  Sufficent_Info       419 non-null    int64 \n",
      " 16  Comment_quality      419 non-null    object\n",
      "dtypes: int64(14), object(3)\n",
      "memory usage: 55.8+ KB\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_excel('CSV_W23.xlsx')\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
